_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.5
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
model:
    value:
        C: 1
        max_iter: 200
project:
    value:
        name: wandb_epochs_example
        run_name: run_epochs_logistic
train:
    value:
        epochs: 10
